float errorRunSum=0;
float previousError=0;
float stepperMaxValue=2500.;
float PID_Kp = 10;
float PID_Ki = 0.1;
float PID_Kd = 0.1;
float PID_target = 500;
float PID_updaterate = 200; // ms
bool PID_active=false;
